language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^v.*$/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon/
    - $HOME/.android/build-cache/

env:
  global:
  - TERM=dumb
  - DX_HEAP_SIZE=1536
  - secure: "XcGPMdYdcDCrWZNWJKZDmmUX2BKkpaInTWF/OqInDHSAP8Qib/xw69YZvHGBUP9GBQ+C+9OzrCT0Kmg+d0SyS+uz8W6Yc9FzgDLs07lVyCGDpQKaTpcyct2nmh8+3iZiMYnlSYjgpZqwXKOC1cvrVcX8jA/NtwXhVVJHsaVKP0mV8Hw0hibxNTU+V+vl1rICePcLNe8WZnIe/ESn1cuFb/o2aUjENmIVD74hJIgjRph+YeZXerKbnjHU5IvNoSHnp25exUoH3COUwPabpt142EXKXOIqHs5OiqmlrnjuFrSe7/WKVgjKpAN/daVhKut0JlAMviU05Naj/sv/J+Zsqa6RkW4va/GP+qlmkSjgz7qJLp8OZfknxim1VhaOCdgoWi6fHSN5LeVXu4COjUg5G3hyfVSBRIydVOj68KulUBSvnxmC5NszdUaprivENy8FGkxqImZM2GeqlqlYtPis7GZQsmXjyva9IDWVaNy7XEl5w4fpW3Y5XEX0ITOUwcUmQ7D41CelYlg5gFXRdUn/5Xyl5obb58GkxJ5TNAp84cjqAubjpB0lVuhqK7izrRYq7bQLwY2M5VZSuDxX9liJK0SztjAs63MYeuZz/fgKDn7rqRKCUzM9kA1hOAcXyx1KpBKL9cVFIltswSgDyBTYl6OqpygVjHiNOLdEPuO3kSs="
  - secure: "biJ1oYHr0J7wMouHbUbJ95zBDs63WzdmRwMjY3vydZGPn6brKsQNCvI+/bIjGqg7U03u06WRRQmuPO9bTjNbKj3H3pLn68nubAqz8YTNJvXdGZNowp8SoaTKeVBqVZXNTpcYmK3EBgAukSFGztC76TIg5+U7pO+X3Rc/ds/QMV3cJkgflcVndnwrCbN05szszUMD3n4s5MHtQ+KHyWwQXs3hl/i7wD6Yq8qUITmn1gHqzc6SxebiNo/kAF19+yQp2L6n0+JKPYlUSe88z1W8JEyNM1j4ohUM5OV7UtgYpJ9OqWIPBluV64ky5RMZBKA1mVxo3rLJ0SGTvZKAmQTiznnxKOxorfsQbRFt3DI8Bt1PoGcZsfTMVoE2vv7ycbCxaLQEZjf+DP44nFRDvdlwLuQlYTauYWDXsyQaeg7m0KfDhXJKH4cn2lSjDOMbR1Ym7xPMkoilAf7LhDG4PQ/RzM0L/ic97VZqnLAZAw+Sf62BDjHhoHANsjDqBNI/1LpVQ1QGII4wjU9J7b7ktmyc3+fjcqIKCpWchEZ3V+F1gjIem1UbLJekkbiFnrtMdOn8HiCwulglnxejrt6PBXvXr6hA5qy6tYDMbLI+j/RP/4Z0MvQ8Irt9xM3tupd0dSnqzTwUtTVYB4jFpcANaL3KxfTktxu478urIrf1d57okVU="

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - "export TRAVIS_LAST_COMMIT_MSG=\"$(git log --format=%s --no-merges -n 1)\""
  - sudo pip install tweepy
  - source version.properties
  - export MAJOR MINOR PATCH

# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true  # if we don't skip install, ./gradlew assemble is invoked, but this task is not available.

before_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH  # ensure our tools are prefered over included ones.
  - export ARTIFACTORY_DEPLOY="true"

script:
  - ./gradlew buildPlugin
  - ./gradlew test
  - ./gradlew ktlintCheck
  - ./gradlew detektCheck

deploy:
  - provider: script
    script:
      - travis/publishToJetBrains.sh
    skip_cleanup: true
    all_branches: true
    on:
      tags: true

  - provider: script
    script:
      - travis/publishToBintray.sh
    on:
      branch: master
    skip_cleanup: true

after_deploy:
  - travis/createTweetAfterDeployOnTag.sh
